site_name: Augchem
site_url: https://gbonavina.github.io/AugChem/
site_description: Documentation for Augchem - a chemical data augmentation toolbox created in partnership with CINE and FAPESP.
site_author: Gabriel Bonavina

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - header.autohide
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

  logo: assets/logo.ico?v=3
  favicon: assets/logo.png?v=3

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            merge_init_into_class: true
            show_signature: true
            show_signature_annotations: true
            show_root_heading: true
            show_object_full_path: false
            heading_level: 2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gbonavina/AugChem
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/augchem

nav:
  - Home: index.md
  - Tutorials:
      - Overview: tutorial.md
      - SMILES Tutorial: smiles_tutorial.md
      - Graph Tutorial: graph_tutorial.md
  - Examples:
      - Overview: examples.md
      - SMILES Examples: smiles_examples.md
      - Graph Examples: graph_examples.md
  - API Reference:
      - Augchem: reference/augchem.md
      - Loader: reference/loader.md
      - Methods:
        - SMILES Methods: reference/smiles_methods.md
        - Graphs Methods: reference/graphs_methods.md
        # - INCHI Methods: reference/inchi_methods.md
      - Modules:
        - SMILES Module: reference/smiles_module.md
        - Graphs Module: reference/graphs_module.md
        # - INCHI Module: reference/inchi_module.md
        
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
